# Generated by Django 3.2.4 on 2021-06-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResCivilId', models.CharField(max_length=50)),
                ('ResName', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(0, 'Kuwait City'), (1, 'Al Jahra'), (2, 'Hawalli'), (3, 'Farwaniyah'), (4, 'Mubarak Al-Kabeer'), (5, 'Al Ahmadi')])),
                ('Accident_Address', models.TextField(blank=True, null=True)),
                ('Accident_Describtion', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Two car crash'), (1, 'Multi car crash'), (2, 'Car crash with Injury'), (3, 'Car crash with Death'), (4, 'Car crash with Fire')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('RoadStatus', models.IntegerField(choices=[(0, 'No Traffic Delays'), (1, ' Medium Amount of Traffic'), (2, ' traffic delays')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('civilid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accident_type', models.IntegerField(choices=[(0, 'New Report'), (1, 'In Progress'), (2, 'Done')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.receiver')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='receivers',
            field=models.ManyToManyField(through='report.ReportStatus', to='report.Receiver'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reporter'),
        ),
    ]
