# Generated by Django 3.2.4 on 2021-06-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Accident_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Road_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='receiver',
            name='ResCivilId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='civilid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accident_type', models.IntegerField(choices=[(0, 'New Report'), (1, 'In Progress'), (2, 'Done')], default=0)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('Reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reporter')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.receiver')),
            ],
        ),
    ]
