# Generated by Django 3.2.4 on 2021-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_reportstatus_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.IntegerField(choices=[('KuwaitCity', 'Kuwait City'), ('AlJAhra', 'Al Jahra'), ('Hawalli', 'Hawalli'), ('Farwaniyah', 'Farwaniyah'), ('MubarakAlkabeer', 'Mubarak Al-Kabeer'), ('AlAhmad', 'Al Ahmadi')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[(0, 'Two car crash'), (1, 'Multi car crash'), (2, 'Car crash with Injury'), (3, 'Car crash with Death'), (4, 'Car crash with Fire')], max_length=50),
        ),
    ]
