# Generated by Django 3.2.4 on 2021-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210624_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('KuwaitCity', 'Kuwait City'), ('AlJAhra', 'Al Jahra'), ('Hawalli', 'Hawalli'), ('Farwaniyah', 'Farwaniyah'), ('MubarakAlkabeer', 'Mubarak Al-Kabeer'), ('AlAhmad', 'Al Ahmadi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Two car crash', 'Two car crash'), ('Multi car crash', 'Multi car crash'), ('Car crash with Injury', 'Car crash with Injury'), ('Car crash with Death', 'Car crash with Death'), ('Car crash with Fire', 'Car crash with Fire')], max_length=50),
        ),
    ]
