# Generated by Django 3.2.4 on 2021-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Two', 'Two car crash'), ('Multi', 'Multi car crash'), ('Injury', 'Car crash with Injury'), ('Death', 'Car crash with Death'), ('Fire', 'Car crash with Fire')], max_length=50),
        ),
    ]
