# Generated by Django 3.2.4 on 2021-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Two car crash'), (1, 'Multi car crash'), (2, 'Car crash with Injury'), (3, 'Car crash with Death'), (4, 'Car crash with Fire')]),
        ),
    ]
